MQTT_HOST = "xxxxx.s1.eu.hivemq.cloud"
MQTT_PORT = 8883
MQTT_USERNAME = "usuario"
MQTT_PASSWORD = "password"

MQTT_TOPIC_TELEMETRY = "factory/demo/tank01/telemetry"
MQTT_TOPIC_RECOMMENDATION = "factory/demo/tank01/recommendation"
MQTT_TOPIC_ALARM = "factory/demo/tank01/alarm"
